[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"


[project]
name = "QMatch"
version = "0.0.0"
requires-python = ">=3.7"
dependencies = [
    "numpy",
    "matplotlib",
    "scipy"
]


[tool.setuptools]
packages = ["QMatch"]
